Support auth header
bloXroute-Labs/serum-client-python pull request #20
Opened 2022-08-03 22:22 UTC by huangzhen1997

2022-08-03 22:53 UTC, kdonthi commented on bxserum/provider/ws.py
> +        self.auth_header = auth_header
Is this line necessary?

2022-08-03 22:56 UTC, kdonthi commented on bxserum/provider/constants.py
> +AUTH_HEADER = "Your Auth Header"
Would it be better to have the AUTH_HEADER as an environment variable so that it can be used across different SDKs?

2022-08-03 22:56 UTC, kdonthi approved these changes

2022-08-04 18:11 UTC, aspin requested changes
some clean up needed. I think you also need to update the requirements.txt to get the latest bx-jsonrpc-py

2022-08-04 18:11 UTC, aspin commented on bxserum/provider/grpc.py
> +import importlib_metadata
what's this import used for?

2022-08-04 18:11 UTC, aspin commented on bxserum/provider/http.py
> +        self._session.headers.__setitem__("authorization", auth_header)
pretty sure you can do `self._session.headers["authorization"] = auth_header`. prefer not to use `__setitem__` unless completely necessary

2022-08-04 18:11 UTC, aspin commented on bxserum/provider/http_error.py
> +from aiohttp import ContentTypeError
unneeded?

2022-08-04 18:11 UTC, aspin commented on bxserum/provider/ws.py
> +import websockets.datastructures
this also loks unused?

2022-08-04 18:11 UTC, aspin commented on bxserum/provider/constants.py
> +AUTH_HEADER = "Your Auth Header"
+1

I'd suggest deleting this though, and exposing a function to load AUTH_HEADER from the environment and or defining it as a constant in the examples. Since this code isn't used in the SDK library itself, it shouldn't be in here –– it's only used in the examples, so it can be defined in those files.

2022-08-05 16:30 UTC, aspin approved these changes

2022-08-05 16:30 UTC, aspin commented on example/transaction/main.py
> +from bxserum.provider import constants
unused i think

2022-08-05 17:33 UTC, merged