TRAD-230 Convert pools endpoint from POST to GET
bloXroute-Labs/serum-client-python pull request #31
Opened 2022-10-04 14:36 UTC by yobloxroute

2022-10-04 15:38 UTC, aspin requested changes
formatting change needed

2022-10-04 15:38 UTC, aspin commented on bxsolana/provider/http.py
> +            self,
If you're using PyCharm, set the continuation indent to be 4 instead of 8.

Alternatively, run `make fmt`

2022-10-05 12:01 UTC, yobloxroute commented on bxsolana/provider/http.py
> +            self,
yeah, didn't configured IDE properly

2022-10-05 15:10 UTC, aspin approved these changes

2022-10-05 15:27 UTC, merged