Using solana-trader-proto
bloXroute-Labs/serum-client-python pull request #39
Opened 2022-12-05 16:56 UTC by tinystarinagalaxy

2022-12-05 18:55 UTC, atulsriv commented on README.md
> +    cd /Users/mahmoud/Documents/workspace-go/solana-trader-proto/
remove the /Users/mahmoud

2022-12-05 18:56 UTC, atulsriv requested changes, later dismissed

2022-12-05 18:56 UTC, atulsriv commented on requirements.txt
> +solana-trader-python-proto==0.0.6
will we have to tag a new proto version during development to test changes?

2022-12-05 18:58 UTC, tinystarinagalaxy commented on requirements.txt
> +solana-trader-python-proto==0.0.6
no, during developement, you dont need any version changes

2022-12-06 21:01 UTC, tinystarinagalaxy commented on README.md
> +    cd /Users/mahmoud/Documents/workspace-go/solana-trader-proto/
done

2022-12-06 21:26 UTC, aspin requested changes
1 more request for installing from git

2022-12-06 21:26 UTC, aspin commented on .circleci/config.yml
> +      - examples-mainnet:
run both testnet and mainnet here

2022-12-06 21:26 UTC, aspin commented on README.md
> +
add an example for installing from `git` for CI builds

2022-12-06 21:26 UTC, aspin commented on README.md
> +    rm -rf python/dist/
this step isn't necessary for making the protobuf files, only for packaging the protobuf, so move it down to line 81

2022-12-06 21:29 UTC, tinystarinagalaxy commented on README.md
> +
i have to figure this out later

2022-12-06 21:29 UTC, tinystarinagalaxy commented on README.md
> +    rm -rf python/dist/
moved

2022-12-06 21:30 UTC, tinystarinagalaxy commented on .circleci/config.yml
> +      - examples-mainnet:
done

2022-12-06 21:44 UTC, aspin approved these changes

2022-12-06 22:48 UTC, merged