[WIP] Refactor Python SDK Integration Tests into modules
bloXroute-Labs/serum-client-python pull request #42
Opened 2022-12-13 23:30 UTC by atulsriv

mainly opening this PR right now to make use of circleci integration test related things

2022-12-14 18:05 UTC, aspin requested changes
good idea, but I don't think `utils` is the right name for this module. maybe `example`?

2022-12-14 18:05 UTC, aspin commented on bxsolana/utils/order_utils.py
> +                            owner_addr,
make sure you run the linter + formatter

2022-12-14 18:05 UTC, aspin commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
typically after this you want to define an `__all__` block to name all the exports you want to include. Do you really need to export everything? `do_requests`/`do_transaction_request`/`do_stream` seem like the only things needed

2022-12-14 18:13 UTC, atulsriv commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
the others are exported because I split it across different files, I'll look into a workaround or just put it into one file

2022-12-14 18:14 UTC, atulsriv commented
> good idea, but I don't think `utils` is the right name for this module. maybe `example`?

Yeah, I think `examples` is fine

2022-12-14 18:14 UTC, atulsriv commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
oh, I think I can use the `__all__` block to accomplish this

2022-12-14 18:17 UTC, aspin commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
yeah, but I think you can keep everything else as private to this module. `__init__.py`/`__all__` are meant to define the exports you want from this module. Are you calling stuff like `place_order` explicitly elsewhere? Because that's used in `example/provider` is `do_stream` and like functions.

2022-12-14 18:19 UTC, atulsriv commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
well it's just that I split up the `order_lifecycle` function in its own file (no real reason). nothing is explicitly called outside the module

2022-12-14 18:29 UTC, aspin commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
Ah, I see what you did. Typically when you're within a module you don't want to import the module itself. Like when you're in `utils/order_lifecycle.py`, don't import `utils`. Instead, do `from .order_utils import ...`

2022-12-14 18:29 UTC, aspin commented on bxsolana/utils/__init__.py
> +from .order_lifecycle import order_lifecycle
you can end up in weird dependency circles if you dont do that

2022-12-15 16:57 UTC, aspin approved these changes
good once linter passes

2022-12-19 18:28 UTC, merged