add support for bundling
bloXroute-Labs/serum-client-python pull request #98
Opened 2024-01-29 16:02 UTC by atulsriv

2024-02-07 00:14 UTC, DimaCantemir requested changes

2024-02-07 00:14 UTC, DimaCantemir commented on bxsolana/provider/ws.py
> +        endpoint: str = constants.TESTNET_API_WS,
revert to prod please

2024-02-07 00:14 UTC, DimaCantemir commented on bxsolana/transaction/private_txs.py
> +    "AFT8VayE7qr8MoQsW3wHsDS83HhEvhGWdbNSHRKeUDfQ"
I would not hardcode but document and let the user get the fresh one from our docs

2024-02-07 00:14 UTC, DimaCantemir commented on example/bundles/main.py
> +    # await ws()
uncomment or remove please

2024-02-07 00:14 UTC, DimaCantemir commented on example/bundles/main.py
> +    # await http()
same as above

2024-02-13 15:41 UTC, tinystarinagalaxy approved these changes

2024-02-13 17:46 UTC, etienneblxr approved these changes

2024-02-13 18:26 UTC, DimaCantemir approved these changes

2024-02-13 18:54 UTC, merged